export enum ThemeColor {
  LIGHT = 'light',
  DARK = 'dark',
}

export enum StatusColor {
  Success = 'success',
  Info = 'info',
  Warning = 'warning',
  Danger = 'danger',
}

export enum InterfaceName {
  AddPauser = 'AddPauser',
  AddVerified = 'AddVerified',
  Allowance = 'Allowance',
  Approve = 'Approve',
  ApproveAndCall = 'ApproveAndCall',
  AuthorizeOperator = 'AuthorizeOperator',
  BalanceOf = 'BalanceOf',
  BalanceOf1 = 'BalanceOf1',
  BalanceOfBatch = 'BalanceOfBatch',
  Burn = 'Burn',
  Burn1 = 'Burn1',
  BurnFrom = 'BurnFrom',
  CancelAndReissue = 'CancelAndReissue',
  ImplementInterfaceForAddress = 'ImplementInterfaceForAddress',
  Cap = 'Cap',
  Decimals = 'Decimals',
  DecreaseAllowance = 'DecreaseAllowance',
  DecreaseAllowanceAndCall = 'DecreaseAllowanceAndCall',
  DecreaseSupply = 'DecreaseSupply',
  DefaultOperators = 'DefaultOperators',
  GetApproved = 'GetApproved',
  GetCurrentFor = 'GetCurrentFor',
  Granularity = 'Granularity',
  HasHash = 'HasHash',
  HolderAt = 'HolderAt',
  HolderCount = 'HolderCount',
  IncreaseAllowance = 'IncreaseAllowance',
  IncreaseAllowanceAndCall = 'IncreaseAllowanceAndCall',
  IncreaseSupply = 'IncreaseSupply',
  IsApprovedForAll = 'IsApprovedForAll',
  IsHolder = 'IsHolder',
  IsPauser = 'IsPauser',
  IsOperatorFor = 'IsOperatorFor',
  IsSuperseded = 'IsSuperseded',
  IsVerified = 'IsVerified',
  Mint = 'Mint',
  Name = 'Name',
  OnErc721Received = 'OnErc721Received',
  OnErc1155BatchReceived = 'OnErc1155BatchReceived',
  OnErc1155Received = 'OnErc1155Received',
  OperatorBurn = 'OperatorBurn',
  OperatorSend = 'OperatorSend',
  OwnerOf = 'OwnerOf',
  RemoveVerified = 'RemoveVerified',
  RenouncePauser = 'RenouncePauser',
  RevokeOperator = 'RevokeOperator',
  SafeBatchTransferFrom = 'SafeBatchTransferFrom',
  SafeTransferFrom = 'SafeTransferFrom',
  SafeTransferFrom1 = 'SafeTransferFrom1',
  Send = 'Send',
  SetApprovalForAll = 'SetApprovalForAll',
  SupportsInterface = 'SupportsInterface',
  Symbol = 'Symbol',
  TokensReceived = 'TokensReceived',
  TokensToSend = 'TokensToSend',
  TokenByIndex = 'TokenByIndex',
  TokenOfOwnerByIndex = 'TokenOfOwnerByIndex',
  TokenUri = 'TokenUri',
  TotalSupply = 'TotalSupply',
  Transfer = 'Transfer',
  Transfer1 = 'Transfer1',
  Transfer2 = 'Transfer2',
  TransferAndCall = 'TransferAndCall',
  TransferFrom = 'TransferFrom',
  TransferFromAndCall = 'TransferFromAndCall',
  UpdateVerified = 'UpdateVerified',
  URI = 'URI',
  Pause = 'Pause',
  Paused = 'Paused',
  Unpause = 'Unpause',
  MintWithTokenURI = 'MintWithTokenURI',
}

export enum ErcName {
  Erc20 = 'Go20',
  Erc20Burnable = 'Go20Burnable',
  Erc20Capped = 'Go20Capped',
  Erc20Detailed = 'Go20Detailed',
  Erc20Mintable = 'Go20Mintable',
  Erc20Pausable = 'Go20Pausable',
  Erc165 = 'Go165',
  Erc721 = 'Go721',
  Erc721Receiver = 'Go721Receiver',
  Erc721Metadata = 'Go721Metadata',
  Erc721Enumerable = 'Go721Enumerable',
  Erc721Pausable = 'Go721Pausable',
  Erc721Mintable = 'Go721Mintable',
  Erc721MetadataMintable = 'Go721MetadataMintable',
  Erc820 = 'Go820',
  Erc1155 = 'Go1155',
  Erc1155Receiver = 'Go1155Receiver',
  Erc1155Metadata = 'Go1155Metadata',
  Erc223 = 'Go223',
  Erc621 = 'Go621',
  Erc777 = 'Go777',
  Erc777Receiver = 'Go777Receiver',
  Erc777Sender = 'Go777Sender',
  Erc827 = 'Go827',
  Erc884 = 'Go884',
}
